name: Upload to PyPI

on:
  release:
    types: [published]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install build setuptools wheel twine

    - name: Package project
      run: |
        make build

    - name: Upload package
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: |
        make push
